### ISSUE TITLE
Add correct movie thumbnail

### ISSUE THREAD

**Issue by mitchiemt11** [mitchiemt11/trailers-trove#3]
The current data has a default thumbnail for all movies. Add a correct thumbnail on each movie title without breaking the UI.

**Comment by Piyush07p** [comment]
can u assign it to me

**Comment by jobs-code** [comment]
@mitchiemt11 if the issue is still open, can I work on this? 
if it is so please assign to me.

**Comment by mitchiemt11** [comment]
@jobs-code Drop a PR when you are done. I will merge asap.

**Comment by jobs-code** [comment]
@mitchiemt11 #26 please check.

**Comment by mitchiemt11** [comment]
@jobs-code PR is fine. I've merged. Thanks!

**Comment by mitchiemt11** [comment]
@jobs-code I'm thinking of some lil changes 🤔 .

**Comment by mitchiemt11** [comment]
How about having the thumbnail be the background image? This will completely remove the background image in the data object and the user is able to view the same thumbnail when the movie is selected/focused. In doing so, we'll do away with that default creed image path which renders when component mounts but we'll have the first result of the trailers [0] which should still be Creed 3

**Comment by mitchiemt11** [comment]
@jobs-code are you up for this?

**Comment by mitchiemt11** [comment]
Ok, thanks! 
I'm happy to close this

**Comment by mitchiemt11** [comment]
Connected! 
Don't forget to star the repo 😉
