### ISSUE TITLE
Handle search filter when no results are found

### ISSUE THREAD

**Issue by mitchiemt11** [mitchiemt11/trailers-trove#9]
If the user search for a movie trailer which is unavailable on the list, there should be a simple text at the centre of the page. Something like: "Oops!, No results found"

**Comment by Mogoww** [comment]
Hello,


> If the user search for a movie trailer which is unavailable on the list, there should be a simple text at the centre of the page. Something like: "Oops!, No results found"

Hello,

I am interested in the task mentioned in the GitHub issue description regarding adding a "Oops!, No results found" message to the center of the page when a user searches for a movie that is not available in the list of trailers. Is it possible to assign this task to me? I would be delighted to contribute to this feature

**Comment by mitchiemt11** [comment]
Hi @Mogoww .  I've assigned this to you. Drop a PR when you are done, I will merge asap. Thanks!

**Comment by Piyush07p** [comment]
@mitchiemt11  can u assign it to me

**Comment by mitchiemt11** [comment]
> @mitchiemt11 can u assign it to me

Sorry @Piyush07p I've merged a PR for this one.

**Comment by mitchiemt11** [comment]
Closing the issue.
